vis/owners/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from . import views
app_name='owners'
urlpatterns = [
    path('physical_person',views.physical_personIndex,name='physical_person'),
    path('juridic_person',views.juridic_personIndex,name='juridic_person'),
    path('report_owners',views.reportIndex,name='report_owners')

]

vis/vaccines/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from . import views
app_name='vaccines'
urlpatterns = [
    path('arrival',views.arrivalIndex,name='arrival'),
    path('handbook',views.handbookIndex,name='handbook'),
    path('distribution',views.distributionIndex,name='distribution'),
    path('consumption_rate',views.consumption_rateIndex,name='consumption_rate'),
    path('report_vaccines',views.reportIndex,name='report_vaccines')
]   

vis/vis/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('login',views.LoginPage,name='login'),
    path('owners/',include('owners.urls'),name='owners'),   
    path('vaccines/',include('vaccines.urls'),name='vaccines'),
    path('vaccination/',include('vaccination.urls'),name='vaccination'),
    path('diagnostics/',include('diagnostics.urls'),name='diagnostics'),
    path('interactions/',include('interactions.urls'),name='interactions'),
    path('monitoring/',include('monitoring.urls'),name='monitoring'),
    path('information_services/',include('information_services.urls'),name='information_services'),
    path('adminstration_system/',include('adminstration_system.urls'),name='adminstration_system'),
    path('security/',include('security.urls'),name='security'),
]

vis/vaccines/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def arrivalIndex(request):
    context={}

    return render(request,'vaccines/arrival/index.html',context)

def handbookIndex(request):
    context={}
    return render(request,'vaccines/handbook/index.html',context)

def distributionIndex(request):
    context={}
    return render(request,'vaccines/distribution/index.html',context)

def consumption_rateIndex(request):
    context={}
    return render(request,'vaccines/consumption_rate/index.html',context)

def reportIndex(request):
    context={}
    return render(request,'vaccines/report/index.html',context)

vis/templates/vaccines/report/index.html
{% extends 'base_site.html'%}

{% load static %}

{% block title %}
Dashboard
{% endblock title %}

{% block stylesheets %}
{{block.super}}
<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
<link href="{% static 'plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" />


<!-- ================== END PAGE LEVEL STYLE ================== -->
{% endblock stylesheets %}

{% block content%}
<div id="content" class="content">
    <!-- begin breadcrumb -->
    <!-- <ol class="breadcrumb float-xl-right">
        <li class="breadcrumb-item"><a href="{% url 'index'%}">Дома</a></li>
        <li class="breadcrumb-item"><a href="javascript:;">Владельцы</a></li>
        <li class="breadcrumb-item active"><a href="{% url 'owners:physical_person' %}">Физическое лицо</a></li>

    </ol> -->
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Отчетность</h1>
    <!-- end page-header -->
    <!-- begin row -->
    
</div>
{% endblock content %}

{% block javascripts %}
{{ block.super}}
<!-- ================== BEGIN PAGE LEVEL JS ================== -->
<script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'js/demo/table-manage-responsive.demo.js ' %}"></script>



<!-- ================== END PAGE LEVEL JS ================== -->
{% endblock javascripts %}